"use client";

import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: { padding: 40, backgroundColor: "#ffffff" },
  header: { fontSize: 24, marginBottom: 20, textAlign: "center", color: "#0D8ABC", fontWeight: "bold" },
  section: { marginBottom: 15 },
  row: { flexDirection: "row", justifyContent: "space-between", marginBottom: 10 },
  label: { fontSize: 12, color: "#666", width: "40%" },
  value: { fontSize: 14, fontWeight: "bold", width: "60%", textAlign: "right" },
  footer: { marginTop: 50, fontSize: 10, color: "#999", textAlign: "center" }
});

interface InvoicePDFProps {
  invoice: {
    invoiceId: string;
    client: string;
    amount: number;
    date: string;
    dueDate: string;
    status: string;
  };
}

export function InvoicePDF({ invoice }: InvoicePDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.header}>FACTURA {invoice.invoiceId}</Text>
        
        <View style={styles.section}>
          <View style={styles.row}>
            <Text style={styles.label}>Client:</Text>
            <Text style={styles.value}>{invoice.client}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Issue date:</Text>
            <Text style={styles.value}>{new Date(invoice.date).toLocaleDateString()}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Due date:</Text>
            <Text style={styles.value}>{new Date(invoice.dueDate).toLocaleDateString()}</Text>
          </View>
          <View style={styles.row}>
            <Text style={styles.label}>Status:</Text>
            <Text style={styles.value}>{invoice.status === 'paid' ? 'Paid' : invoice.status === 'pending' ? 'Pending' : 'Overdue'}</Text>
          </View>
        </View>

        <View style={{ marginTop: 30, padding: 15, backgroundColor: "#f4f4f5", borderRadius: 5 }}>
          <View style={styles.row}>
            <Text style={{ fontSize: 16, fontWeight: "bold" }}>Amount Total:</Text>
            <Text style={{ fontSize: 18, fontWeight: "bold", color: "#0D8ABC" }}>${invoice.amount.toLocaleString()}</Text>
          </View>
        </View>

        <Text style={styles.footer}>Automatically generated by My SaaS - Thank you for your business.</Text>
      </Page>
    </Document>
  );
}